package com.quantumdataengines.app.compass.dao;

public interface Query {
	String GETALLSYSTEMPARAMS = "SELECT PARAMETERNAME, PARAMETERVALUE "+
								"  FROM TB_SYSTEMPARAMETERS";
	/*
	public static final String GETMODULESBYROLE = "SELECT A.MODULECODE MODULECODE, A.MAINORSUBMODULE MAINORSUBMODULE, A.MAINMODULECODE MAINMODULECODE "+
												"  FROM TB_MODULE A, TB_ROLEMODULEMAPPING B "+
												"  WHERE A.MODULECODE = B.MODULECODE "+
												"    AND B.ROLEID = ? " +
												"  ORDER BY DISPLAYORDER";
	public static final String GETMODULESBYUSER = "SELECT A.MODULECODE MODULECODE, A.MAINORSUBMODULE MAINORSUBMODULE, A.MAINMODULECODE MAINMODULECODE "+
												  "  FROM TB_MODULE A, TB_USERMODULEMAPPING B "+
												  "  WHERE A.MODULECODE = B.MODULECODE "+
												  "   AND B.USERCODE = ? " +
												  "  ORDER BY DISPLAYORDER";
	public static final String GETMAINMODULE = "SELECT MODULECODE, MODULENAME, MODULEURL, ISMULTIPLE "+
											   "  FROM TB_MODULE "+
											   " WHERE MODULECODE = ?";
	public static final String GETSUBMODULES = "SELECT MODULECODE, MODULENAME, MODULEURL, ISMULTIPLE "+
											   "  FROM TB_MODULE "+
											   " WHERE MAINMODULECODE = ?"+
											   "   AND MAINORSUBMODULE = 'S'";
	*/
	String GETUSERSASSIGNEDMODULES = "SELECT A.MODULECODE, A.MAINORSUBMODULE, A.MAINMODULECODE"+
						    		 "  FROM TB_USERMODULEMAPPING B, TB_MODULE A"+
						    		 " WHERE A.MODULECODE = B.MODULECODE"+
						    		 "   AND B.USERCODE = ?"+
						    		 "   AND B.ROLEID  = ?"+
									 " ORDER BY A.DISPLAYORDER";
	
	String GETROLEASSIGNEDMODULES = "SELECT A.MODULECODE, A.MAINORSUBMODULE, A.MAINMODULECODE"+
								 	"  FROM TB_ROLEMODULEMAPPING B, TB_MODULE A"+
								 	" WHERE A.MODULECODE = B.MODULECODE"+
								 	"   AND B.ROLEID = ?"+
								 	"   AND B.ISENABLED = 'Y' "+
								 	" ORDER BY A.DISPLAYORDER";
	/*
	String GETMODULEDETAILSBYMAINMODULE = "SELECT MODULECODE, MODULENAME, MODULEURL, MAINORSUBMODULE, MAINMODULECODE, DISPLAYORDER, ISMULTIPLE "+
							  			  "  FROM TB_MODULE A "+
							  			  " WHERE MAINMODULECODE = ?"+
										  " ORDER BY A.DISPLAYORDER";
 	*/
	String GETMODULEDETAILSBYMAINMODULE_CHECKER = "SELECT MODULECODE, MODULENAME, MODULEURL, MAINORSUBMODULE, MAINMODULECODE, DISPLAYORDER, ISMULTIPLE "+
												  "  FROM TB_MODULE A "+
											      " WHERE MAINMODULECODE = ? "+
											      " ORDER BY A.DISPLAYORDER ";

	String GETMODULEDETAILSBYMAINMODULE = "SELECT A.MODULECODE, A.MODULENAME, A.MODULEURL, A.MAINORSUBMODULE, A.MAINMODULECODE, A.DISPLAYORDER, A.ISMULTIPLE "+
										  "  FROM TB_MODULE A, TB_ROLEMODULEMAPPING B "+
										  " WHERE A.MAINMODULECODE = ? "+
										  "   AND A.MODULECODE = B.MODULECODE "+
										  "   AND B.ROLEID = ? "+
										  "   AND B.ISENABLED = 'Y' "+
										  " ORDER BY A.DISPLAYORDER ASC ";

	/*
	String GETMODULEDETAILSBYMAINMODULE = "SELECT A.MODULECODE, A.MODULENAME, A.MODULEURL, A.MAINORSUBMODULE, A.MAINMODULECODE, A.DISPLAYORDER, A.ISMULTIPLE "+
										  "  FROM TB_MODULE A, TB_ROLEMODULEMAPPING B "+
										  " WHERE A.MAINMODULECODE = ? "+
										  "   AND A.MODULECODE = B.MODULECODE "+
										  "   AND B.ROLEID = ? "+
										  " ORDER BY A.DISPLAYORDER";
    */									
	
	String GETMODULEDETAILSBYMODULE = "SELECT MODULECODE, MODULENAME, MODULEURL, MAINORSUBMODULE, MAINMODULECODE, DISPLAYORDER, ISMULTIPLE "+
							  		  "  FROM TB_MODULE A "+
							  		  " WHERE MODULECODE = ?"+
									  " ORDER BY A.DISPLAYORDER";
	
	String CHANGEPROFILEPRIORITY1 = "UPDATE TB_USERROLEMAPPING"+
									"   SET LOGINPRIORITY = 0"+
									" WHERE USERCODE = ?";
	
	String CHANGEPROFILEPRIORITY2 = "UPDATE TB_USERROLEMAPPING"+
									"   SET LOGINPRIORITY = 1"+
									" WHERE USERCODE = ?"+
									"   AND ROLEID = ?";
	
	String ACCOUNTEXPIRY = "UPDATE TB_USER SET ACCOUNTEXPIRED = 'Y' WHERE SYSTIMESTAMP > NVL(ACCOUNTEXIPYDATE, SYSTIMESTAMP)";
	
	String PASSWORDEXPIRY = "UPDATE TB_USER A "+
							"   SET CREDENTIALEXPIRED = 'Y' "+
							" WHERE A.USERCODE IN ( "+
							"SELECT B.USERCODE "+
							"  FROM TB_PASSWORDCHANGELOG B "+
							" GROUP BY B.USERCODE "+
							"HAVING TRUNC(SYSTIMESTAMP) - TRUNC(MAX(UPDATETIMESTAMP)) > ?)";
	
	String EMAILAVAILABLITYCHECK = "SELECT COUNT(*) EMAILCOUNT "+
								   "  FROM TB_EMAILEXCHANGEDETAILS "+
                    			   " WHERE EMAILREFERENCENO = ? "+
                    			   "   AND MESSAGEID = ? "+
                    			   "   AND FOLDERTYPE = ? ";
	
	String SETEMAILREFRESHLOG = "INSERT INTO TB_EMAILREFRESHLOG(REFRESHTIME, EMAILCOUNT, STATUS, MESSAGE, FOLDER, UPDATEDBY, UPDATETIMESTAMP) "+
			   					"VALUES (?,?,?,?,?,?,SYSTIMESTAMP) ";
	
	String GETLASTEMAILREFRESGLOG = "SELECT REFRESHTIME, STATUS, MESSAGE "+
			   						"  FROM TB_EMAILREFRESHLOG "+
			   						" WHERE FOLDER = ?"+
			   						" ORDER BY UPDATETIMESTAMP DESC";
	
	String GETALLEMAILREFRESHLOG = "SELECT REFRESHTIME, EMAILCOUNT, STATUS, MESSAGE, FOLDER, UPDATEDBY "+
								   "  FROM TB_EMAILREFRESHLOG"+
								   " ORDER BY UPDATETIMESTAMP DESC";
	
	/* Search Modules Functionality */
	String GETROLEASSIGNEDMODULESFORSEARCH = "SELECT X.MODULECODE, X.MAINMODULECODE, X.MAINORSUBMODULE "+
			  								 "  FROM ( "+
 									         "       SELECT A.MODULECODE,A.MAINMODULECODE, A.MAINORSUBMODULE, A.DISPLAYORDER "+
									         "         FROM TB_MODULE A "+
									         "        WHERE A.MAINMODULECODE  IN (SELECT MAINMODULECODE FROM TB_MODULE WHERE MAINORSUBMODULE='S') "+
									         "          AND MAINORSUBMODULE ='S' "+
									         "        UNION "+
									         "       SELECT B.MODULECODE, B.MAINMODULECODE, B.MAINORSUBMODULE, B.DISPLAYORDER "+
									         "         FROM TB_MODULE B "+
									         "        WHERE MAINMODULECODE IN "+ 
									         "             (SELECT MAINMODULECODE "+ 
									         "                FROM ( "+
									         "                      SELECT COUNT(DISTINCT MODULECODE), C.MAINMODULECODE "+
									         "                        FROM TB_MODULE C "+
									         "                       GROUP BY C.MAINMODULECODE "+
									         "                      HAVING COUNT(DISTINCT MODULECODE)=1 "+
									         "                     ) "+
									         "             ) "+
									         "       ) X, TB_ROLEMODULEMAPPING Y "+
											 " WHERE X.MODULECODE = Y.MODULECODE "+
											 "	 AND Y.ROLEID = ? "+
											 " ORDER BY X.DISPLAYORDER ";

											 	
}
