//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.15 at 01:15:30 PM IST 
//


package com.quantumdataengines.app.compass.oxm.screening;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for person complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="person">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="name" type="{http://quantumdataengines.com/ws/schema}name"/>
 *         &lt;element name="dateofbirth" type="{http://quantumdataengines.com/ws/schema}dateofbirth"/>
 *         &lt;element name="passportno" type="{http://quantumdataengines.com/ws/schema}passportno"/>
 *         &lt;element name="panno" type="{http://quantumdataengines.com/ws/schema}panno"/>
 *         &lt;element name="customerid" type="{http://quantumdataengines.com/ws/schema}customerid"/>
 *         &lt;element name="accountno" type="{http://quantumdataengines.com/ws/schema}accountno"/>
 *         &lt;element name="otherDetails" type="{http://quantumdataengines.com/ws/schema}otherDetails"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "person", propOrder = {

})
public class Person {

    @XmlElement(required = true, nillable = true)
    protected String name;
    @XmlElement(required = true, nillable = true)
    protected String dateofbirth;
    @XmlElement(required = true, nillable = true)
    protected String passportno;
    @XmlElement(required = true, nillable = true)
    protected String panno;
    @XmlElement(required = true, nillable = true)
    protected String customerid;
    @XmlElement(required = true, nillable = true)
    protected String accountno;
    @XmlElement(required = true, nillable = true)
    protected String otherDetails;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the dateofbirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateofbirth() {
        return dateofbirth;
    }

    /**
     * Sets the value of the dateofbirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateofbirth(String value) {
        this.dateofbirth = value;
    }

    /**
     * Gets the value of the passportno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassportno() {
        return passportno;
    }

    /**
     * Sets the value of the passportno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassportno(String value) {
        this.passportno = value;
    }

    /**
     * Gets the value of the panno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPanno() {
        return panno;
    }

    /**
     * Sets the value of the panno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPanno(String value) {
        this.panno = value;
    }

    /**
     * Gets the value of the customerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * Sets the value of the customerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerid(String value) {
        this.customerid = value;
    }

    /**
     * Gets the value of the accountno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountno() {
        return accountno;
    }

    /**
     * Sets the value of the accountno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountno(String value) {
        this.accountno = value;
    }

    /**
     * Gets the value of the otherDetails property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOtherDetails() {
        return otherDetails;
    }

    /**
     * Sets the value of the otherDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOtherDetails(String value) {
        this.otherDetails = value;
    }

}
