//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:06:26 PM IST 
//


package com.quantumdataengines.app.compass.util.fatca.validfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcavalidfilenotification" xmlns:fnb="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 * 					&lt;DictionaryEntryNm&gt;Type for Record Error FI Group&lt;/DictionaryEntryNm&gt;
 * 					&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;
 * 					&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;
 * 					&lt;VersionEffectiveBeginDt&gt;2014-08-12&lt;/VersionEffectiveBeginDt&gt;
 * 					&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;
 * 					&lt;Description&gt;Contains the type details of Record Error FI Group&lt;/Description&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for FATCARecordErrorFIGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FATCARecordErrorFIGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}SponsorGIIN" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}SponsorNm" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ReportingFIGIIN" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ReportingFINm" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcavalidfilenotification}FATCARecordErrorDetailGrp" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FATCARecordErrorFIGrpType", namespace = "urn:fatca:fatcavalidfilenotification", propOrder = {
    "sponsorGIIN",
    "sponsorNm",
    "reportingFIGIIN",
    "reportingFINm",
    "fatcaRecordErrorDetailGrp"
})
public class FATCARecordErrorFIGrpType {

    @XmlElement(name = "SponsorGIIN", namespace = "urn:fatca:fatcanotificationbase")
    protected String sponsorGIIN;
    @XmlElement(name = "SponsorNm", namespace = "urn:fatca:fatcanotificationbase")
    protected String sponsorNm;
    @XmlElement(name = "ReportingFIGIIN", namespace = "urn:fatca:fatcanotificationbase")
    protected String reportingFIGIIN;
    @XmlElement(name = "ReportingFINm", namespace = "urn:fatca:fatcanotificationbase")
    protected String reportingFINm;
    @XmlElement(name = "FATCARecordErrorDetailGrp", required = true)
    protected List<FATCARecordErrorDetailGrpType> fatcaRecordErrorDetailGrp;

    /**
     * Gets the value of the sponsorGIIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsorGIIN() {
        return sponsorGIIN;
    }

    /**
     * Sets the value of the sponsorGIIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsorGIIN(String value) {
        this.sponsorGIIN = value;
    }

    /**
     * Gets the value of the sponsorNm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSponsorNm() {
        return sponsorNm;
    }

    /**
     * Sets the value of the sponsorNm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSponsorNm(String value) {
        this.sponsorNm = value;
    }

    /**
     * Gets the value of the reportingFIGIIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingFIGIIN() {
        return reportingFIGIIN;
    }

    /**
     * Sets the value of the reportingFIGIIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingFIGIIN(String value) {
        this.reportingFIGIIN = value;
    }

    /**
     * Gets the value of the reportingFINm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReportingFINm() {
        return reportingFINm;
    }

    /**
     * Sets the value of the reportingFINm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReportingFINm(String value) {
        this.reportingFINm = value;
    }

    /**
     * Gets the value of the fatcaRecordErrorDetailGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fatcaRecordErrorDetailGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFATCARecordErrorDetailGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FATCARecordErrorDetailGrpType }
     * 
     * 
     */
    public List<FATCARecordErrorDetailGrpType> getFATCARecordErrorDetailGrp() {
        if (fatcaRecordErrorDetailGrp == null) {
            fatcaRecordErrorDetailGrp = new ArrayList<FATCARecordErrorDetailGrpType>();
        }
        return this.fatcaRecordErrorDetailGrp;
    }

}
