//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:06:26 PM IST 
//


package com.quantumdataengines.app.compass.util.fatca.validfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcavalidfilenotification" xmlns:fnb="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 * 					&lt;DictionaryEntryNm&gt;Type for Record Error (Pooled Report or Account Report) Details&lt;/DictionaryEntryNm&gt;
 * 					&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;
 * 					&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;
 * 					&lt;VersionEffectiveBeginDt&gt;2014-08-12&lt;/VersionEffectiveBeginDt&gt;
 * 					&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;
 * 					&lt;Description&gt;Contains the type details of Record Errors&lt;/Description&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for FATCARecordErrorDetailGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FATCARecordErrorDetailGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCAReportTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}DocTypeIndicCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}DocRefId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}CorrMessageRefId" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}CorrDocRefId" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}RecordLevelErrorCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FieldErrorGrp" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}ActionRequestedGrp"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FATCARecordErrorDetailGrpType", namespace = "urn:fatca:fatcavalidfilenotification", propOrder = {
    "fatcaReportTypeCd",
    "docTypeIndicCd",
    "docRefId",
    "corrMessageRefId",
    "corrDocRefId",
    "recordLevelErrorCd",
    "fieldErrorGrp",
    "actionRequestedGrp"
})
public class FATCARecordErrorDetailGrpType {

    @XmlElement(name = "FATCAReportTypeCd", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected FATCAReportTypeCdType fatcaReportTypeCd;
    @XmlElement(name = "DocTypeIndicCd", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected FatcaDocTypeIndicType docTypeIndicCd;
    @XmlElement(name = "DocRefId", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected String docRefId;
    @XmlElement(name = "CorrMessageRefId", namespace = "urn:fatca:fatcanotificationbase")
    protected String corrMessageRefId;
    @XmlElement(name = "CorrDocRefId", namespace = "urn:fatca:fatcanotificationbase")
    protected String corrDocRefId;
    @XmlElement(name = "RecordLevelErrorCd", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected String recordLevelErrorCd;
    @XmlElement(name = "FieldErrorGrp", namespace = "urn:fatca:fatcanotificationbase")
    protected List<FieldErrorGrpType> fieldErrorGrp;
    @XmlElement(name = "ActionRequestedGrp", namespace = "urn:fatca:fatcanotificationbase", required = true)
    protected ActionRequestedGrpType actionRequestedGrp;

    /**
     * Gets the value of the fatcaReportTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link FATCAReportTypeCdType }
     *     
     */
    public FATCAReportTypeCdType getFATCAReportTypeCd() {
        return fatcaReportTypeCd;
    }

    /**
     * Sets the value of the fatcaReportTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FATCAReportTypeCdType }
     *     
     */
    public void setFATCAReportTypeCd(FATCAReportTypeCdType value) {
        this.fatcaReportTypeCd = value;
    }

    /**
     * Gets the value of the docTypeIndicCd property.
     * 
     * @return
     *     possible object is
     *     {@link FatcaDocTypeIndicType }
     *     
     */
    public FatcaDocTypeIndicType getDocTypeIndicCd() {
        return docTypeIndicCd;
    }

    /**
     * Sets the value of the docTypeIndicCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FatcaDocTypeIndicType }
     *     
     */
    public void setDocTypeIndicCd(FatcaDocTypeIndicType value) {
        this.docTypeIndicCd = value;
    }

    /**
     * Gets the value of the docRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocRefId() {
        return docRefId;
    }

    /**
     * Sets the value of the docRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocRefId(String value) {
        this.docRefId = value;
    }

    /**
     * Gets the value of the corrMessageRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrMessageRefId() {
        return corrMessageRefId;
    }

    /**
     * Sets the value of the corrMessageRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrMessageRefId(String value) {
        this.corrMessageRefId = value;
    }

    /**
     * Gets the value of the corrDocRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCorrDocRefId() {
        return corrDocRefId;
    }

    /**
     * Sets the value of the corrDocRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCorrDocRefId(String value) {
        this.corrDocRefId = value;
    }

    /**
     * Gets the value of the recordLevelErrorCd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecordLevelErrorCd() {
        return recordLevelErrorCd;
    }

    /**
     * Sets the value of the recordLevelErrorCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecordLevelErrorCd(String value) {
        this.recordLevelErrorCd = value;
    }

    /**
     * Gets the value of the fieldErrorGrp property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldErrorGrp property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldErrorGrp().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FieldErrorGrpType }
     * 
     * 
     */
    public List<FieldErrorGrpType> getFieldErrorGrp() {
        if (fieldErrorGrp == null) {
            fieldErrorGrp = new ArrayList<FieldErrorGrpType>();
        }
        return this.fieldErrorGrp;
    }

    /**
     * Gets the value of the actionRequestedGrp property.
     * 
     * @return
     *     possible object is
     *     {@link ActionRequestedGrpType }
     *     
     */
    public ActionRequestedGrpType getActionRequestedGrp() {
        return actionRequestedGrp;
    }

    /**
     * Sets the value of the actionRequestedGrp property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionRequestedGrpType }
     *     
     */
    public void setActionRequestedGrp(ActionRequestedGrpType value) {
        this.actionRequestedGrp = value;
    }

}
