//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.12.23 at 02:06:26 PM IST 
//


package com.quantumdataengines.app.compass.util.fatca.validfile;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;Component xmlns="urn:fatca:fatcanotificationbase" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:xsd="http://www.w3.org/2001/XMLSchema"&gt;
 * 					&lt;DictionaryEntryNm&gt;Original Paper Record Metadata Group Type&lt;/DictionaryEntryNm&gt;
 * 					&lt;MajorVersionNum&gt;1&lt;/MajorVersionNum&gt;
 * 					&lt;MinorVersionNum&gt;0&lt;/MinorVersionNum&gt;
 * 					&lt;VersionEffectiveBeginDt&gt;2014-08-24&lt;/VersionEffectiveBeginDt&gt;
 * 					&lt;VersionDescriptionTxt&gt;Initial Version&lt;/VersionDescriptionTxt&gt;
 * 					&lt;DescriptionTxt&gt;Type for a group that defines the information contained in the IDES Metadata&lt;/DescriptionTxt&gt;
 * 				&lt;/Component&gt;
 * </pre>
 * 
 * 			
 * 
 * <p>Java class for OriginalPaperRecordMetadataGrpType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OriginalPaperRecordMetadataGrpType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PaperRecordRefId"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PaperRecordDocumentTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}FATCAReportTypeCd"/>
 *         &lt;element ref="{urn:fatca:fatcanotificationbase}PaperPoolReportTypeCd" maxOccurs="6" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OriginalPaperRecordMetadataGrpType", propOrder = {
    "paperRecordRefId",
    "paperRecordDocumentTypeCd",
    "fatcaReportTypeCd",
    "paperPoolReportTypeCd"
})
public class OriginalPaperRecordMetadataGrpType {

    @XmlElement(name = "PaperRecordRefId", required = true)
    protected String paperRecordRefId;
    @XmlElement(name = "PaperRecordDocumentTypeCd", required = true)
    protected PaperRecordDocumentTypeCdType paperRecordDocumentTypeCd;
    @XmlElement(name = "FATCAReportTypeCd", required = true)
    protected FATCAReportTypeCdType fatcaReportTypeCd;
    @XmlElement(name = "PaperPoolReportTypeCd")
    protected List<String> paperPoolReportTypeCd;

    /**
     * Gets the value of the paperRecordRefId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPaperRecordRefId() {
        return paperRecordRefId;
    }

    /**
     * Sets the value of the paperRecordRefId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPaperRecordRefId(String value) {
        this.paperRecordRefId = value;
    }

    /**
     * Gets the value of the paperRecordDocumentTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link PaperRecordDocumentTypeCdType }
     *     
     */
    public PaperRecordDocumentTypeCdType getPaperRecordDocumentTypeCd() {
        return paperRecordDocumentTypeCd;
    }

    /**
     * Sets the value of the paperRecordDocumentTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaperRecordDocumentTypeCdType }
     *     
     */
    public void setPaperRecordDocumentTypeCd(PaperRecordDocumentTypeCdType value) {
        this.paperRecordDocumentTypeCd = value;
    }

    /**
     * Gets the value of the fatcaReportTypeCd property.
     * 
     * @return
     *     possible object is
     *     {@link FATCAReportTypeCdType }
     *     
     */
    public FATCAReportTypeCdType getFATCAReportTypeCd() {
        return fatcaReportTypeCd;
    }

    /**
     * Sets the value of the fatcaReportTypeCd property.
     * 
     * @param value
     *     allowed object is
     *     {@link FATCAReportTypeCdType }
     *     
     */
    public void setFATCAReportTypeCd(FATCAReportTypeCdType value) {
        this.fatcaReportTypeCd = value;
    }

    /**
     * Gets the value of the paperPoolReportTypeCd property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paperPoolReportTypeCd property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPaperPoolReportTypeCd().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPaperPoolReportTypeCd() {
        if (paperPoolReportTypeCd == null) {
            paperPoolReportTypeCd = new ArrayList<String>();
        }
        return this.paperPoolReportTypeCd;
    }

}
